added five questions
Tc2r1/Hacktoberfest_Interview_App pull request #141
Opened 2022-10-24 11:26 UTC by amitkroutthedev

added questions in JS from id 11 to id 16.

2022-10-24 15:37 UTC, atiqueakhtar commented
Hi @amitkroutthedev don't we need to add anything in answers.json?? Just curious

2022-10-24 15:47 UTC, amitkroutthedev commented
I was also little confused because there was no ID in answer.json as there was in question.json

2022-10-24 15:49 UTC, amitkroutthedev commented
If there is some error please suggest so that I can change and give a proper pull request

2022-10-24 19:50 UTC, Tc2r1 requested changes

2022-10-24 19:50 UTC, Tc2r1 commented on Languages/JS/questions.json
> +		"id": 12,
This question and shortAns are way too obvious. Please phrase the shortAns as "It is ..." and please dont use the wording of the question itself in the answer, that is a dead give away.

please don't use the word in the shortAns.

"what does a cat eat?"
a) oranges
b) tacos
c) a cat eats mice
d) trees.

making the answer so obvious defeats the point of the app.

2022-10-24 19:50 UTC, Tc2r1 commented on Languages/JS/questions.json
> +		"details": "A closure is simply a function inside another function that has access to the outer function variable. Now, this definition sound pretty much straightforward but the real magic is creat
Please decrease each of your "details" by one sentence.

2022-10-25 21:58 UTC, Tc2r1 approved these changes

2022-10-25 21:59 UTC, merged