added 3 more java questions
Tc2r1/Hacktoberfest_Interview_App pull request #84
Opened 2022-10-18 03:38 UTC by KeysGilbert

## What type of PR is this? (check all applicable)

- [ ] 🚀 Added Name
- [ ] ✨ Feature
- [ ] 🌟 stared the repo
- [ ] 🐛 Grammatical Error
- [X ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
Edited questions.json in Java folder.

## Add Link of GitHub Profile

2022-10-18 04:54 UTC, Tc2r1 commented on Languages/Java/questions.json
> +      "shortAns": "It isolates a thread.",
Please phrase short answers as "It is" etc.

2022-10-18 04:55 UTC, Tc2r1 requested changes
Please  make requested changes.

2022-10-18 20:35 UTC, AndroidLion48 approved these changes
Well Done! Please do not forget to add your name to CONTRIBUTERS.MD list and star the repository. @KeysGilbert

2022-10-19 04:02 UTC, Tc2r1 approved these changes
awaiting you to add name to contributors list.

2022-10-20 01:14 UTC, merged