"Added 3 questions to question.json file and updated contributors.md"
Tc2r1/Hacktoberfest_Interview_App pull request #96
Opened 2022-10-20 07:07 UTC by glitched-sudhanshu

#48
This change adds 3 questions to question.json file related to Android and updated contributors.md

-glitched-sudhanshu

2022-10-20 07:10 UTC, glitched-sudhanshu commented on CONTRIBUTERS.MD
> +| pantbibek21        | [@pantbibek21](https://github.com/pantbibek21)                | 1                |
Sorry, added this name again by mistake.

2022-10-20 17:03 UTC, AndroidLion48 requested changes
rephrase your short answer from ("small chunks." to "small amounts of data.")

2022-10-20 17:03 UTC, AndroidLion48 commented on Languages/Android/questions.json
> +      "shortAns": "It is used to load in the form of small chunks.",
May you rephrase your short answer from ("small chunks." to "small amounts of data.")? @glitched-sudhanshu 

Thank you for participation!

2022-10-21 04:35 UTC, Tc2r1 approved these changes
This looks great, would you be interested in doing small work on the android project? @glitched-sudhanshu  please don't forget to star the repo.

2022-10-21 05:59 UTC, glitched-sudhanshu commented
Yes, I would like to work on this project.
Can you please elaborate what exactly I will have to do?

Thank you

On Fri, Oct 21, 2022 at 10:05 AM Nudennie ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> This looks great, would you be interested in doing small work on the
> android project? @glitched-sudhanshu
> <https://github.com/glitched-sudhanshu> please don't forget to star the
> repo.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Tc2r1/Hacktoberfest_Interview_App/pull/96#pullrequestreview-1150317173>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQMJ6HRCVZOS3K5SPTVAMMLWEIMSPANCNFSM6AAAAAARJ2PNDE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-22 00:44 UTC, Tc2r1 commented
> Yes, I would like to work on this project. Can you please elaborate what exactly I will have to do? Thank you

Hi, so currently the application is a project consisting of a bunch of modules that all build the same application using different frameworks/libraries.  Currently they all build to show an android Quiz by pulling the information from the languages/android folder. 

There are a few different ways you can contribute to the project.
1) Add a screen that allows you to pick different types of quizzes and flesh out the repository layer to handle loading different types of quizes. 

2) Make splash screens for one of the pre-existing modules

3) Copy a template module (or in the case that you want to make the app in something besides native kotlin or android, use the template as reference) and recreate the application in your own image using your own selection of libraries, (Like Hilt for example) 

There is documentation for these options in the original readme for the project. 

To build the project, after you have the project on your local computer, open the `Interview_Prep_App` folder in Android studio  and it will compile the project, then select whichever module you'll work in and go from there. 

All Modules share the resources from the sharedResources Module.  If you have any questions please post them in discussions or an issue. What do you think?

2022-10-22 09:47 UTC, merged

2022-10-22 11:28 UTC, glitched-sudhanshu commented
Hii Nudennie,

Yeah sure, I will work on it. Once I go through the project I will update
you on which part of the app I am willing to work on.

Just a request, if you are comfortable, can you please provide me with your
linkedIn or Twitter handle, so that we can communicate there. It's a little
bit tedious for me to communicate over emails.
Hope you understand.
Thanks.

On Sat, Oct 22, 2022 at 6:14 AM Nudennie ***@***.***> wrote:

> Yes, I would like to work on this project. Can you please elaborate what
> exactly I will have to do? Thank you
>
> Hi, so currently the application is a project consisting of a bunch of
> modules that all build the same application using different
> frameworks/libraries. Currently they all build to show an android Quiz by
> pulling the information from the languages/android folder.
>
> There are a few different ways you can contribute to the project.
>
>    1.
>
>    Add a screen that allows you to pick different types of quizzes and
>    flesh out the repository layer to handle loading different types of quizes.
>    2.
>
>    Make splash screens for one of the pre-existing modules
>    3.
>
>    Copy a template module (or in the case that you want to make the app
>    in something besides native kotlin or android, use the template as
>    reference) and recreate the application in your own image using your own
>    selection of libraries, (Like Hilt for example)
>
> There is documentation for these options in the original readme for the
> project.
>
> To build the project, after you have the project on your local computer,
> open the Interview_Prep_App folder in Android studio and it will compile
> the project, then select whichever module you'll work in and go from there.
>
> All Modules share the resources from the sharedResources Module. If you
> have any questions please post them in discussions or an issue. What do you
> think?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Tc2r1/Hacktoberfest_Interview_App/pull/96#issuecomment-1287561789>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQMJ6HW6SJV4TZQTFSLOO33WEM2GZANCNFSM6AAAAAARJ2PNDE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-24 15:08 UTC, Tc2r1 commented
@glitched-sudhanshu  I agree it is SO TEDIOUS, unfortunately I dont use twitter or linkedin as often as I should either, could you create an issue ticket and we can communicate there. If you need real help I can setup a zoom call btw.

2022-10-25 21:50 UTC, Tc2r1 commented
@glitched-sudhanshu  feel free to contact me on google chat / hangouts (nudenniew@gmail.com)